# language: node_js
# node_js:
#   - "10"

# cache:
#   directories:
#     - "node_modules"

# branches:
#   only:
#   - master

# install:
#   - npm install
#   - npm run build

# script:
#   - echo "Skipping tests"

# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_ACCESS_TOKEN  # Set in travis-ci.org dashboard, marked secure https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token
#   target-branch: gh-pages
#   local-dir: .vuepress/dist
#   on:
#     branch: main

language: node_js
node_js:
    - "10"
env:
    - CXX=g++-4.8
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
install:
    - npm install
script:
    - npm run build
cache:
    directories:
        - "node_modules"
notifications:
    email: false
deploy:
    provider: pages
    skip-cleanup: true
    local_dir: docs/.vuepress/dist
    github-token: $GITHUB_TOKEN
    repo: thinkwave/thinkwave.github.io
    keep-history: true
    target-branch: main
    on:
        branch: main